### ISSUE TITLE
Configuration not created at install

### ISSUE THREAD

**Issue by waazdakka** [vvanholl/smsgateway-gammu#1]
Hello !
I just installed the gateway on my pi, but it seems I have an little issue : the configuration file has not been created, so I created the file using your example.
But I'm not sure what to use on the "server :" parameter for exampe.

It would be really helpfull to succeed with your tool !!

Thanks !

**Comment by abazad** [comment]
hello bro i had same problem.

but i solved.

the problem is tab space :)

you can edit as in image :)

![Snipaste_2021-02-13_15-55-37](https://user-images.githubusercontent.com/4947845/107850510-0360aa00-6e14-11eb-9dac-c20e8c19cd14.png)
